language: python
python:
    - 3.7
sudo: required
services:
    - docker
install:
    - make dev-env
script:
    - set -e
    - make test/docs docs
    - make build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"
