#!/bin/bash

# Tag the latest build with a date tag mentioned in the notebook folder.
# Push the tag in addition to the "latest" tag already pushed.
TAG=$(cat tag)
docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
docker push $DOCKER_REPO:$TAG
