#!/bin/bash

# Tag the latest build with a date tag mentioned in the notebook folder.
# Push the tag in addition to the "latest" tag already pushed.
TAG=$(cat tag)
docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
docker push $DOCKER_REPO:$TAG

# Invoke all downstream build triggers.
for url in $(echo $NEXT_BUILD_TRIGGERS | sed "s/,/ /g")
do
    curl -X POST $url
done
